version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rag-backend
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CORS_ORIGINS=["http://localhost:3000","http://localhost"]
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - CHUNK_SIZE=500
      - CHUNK_OVERLAP=100
      - TOP_K_RESULTS=5
    volumes:
      - ./backend/data:/app/data
      - ./backend/.env:/app/.env:ro
    networks:
      - rag-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rag-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - rag-network
    restart: unless-stopped

networks:
  rag-network:
    driver: bridge

volumes:
  rag-data: